### ISSUE TITLE
What is the purpose of Table's ShortCaption?

### ISSUE THREAD

**Issue by rnwst** [jgm/pandoc-types#103]
The Table Block currently includes the [Caption](https://hackage.haskell.org/package/pandoc-types-1.22.2.1/docs/Text-Pandoc-Definition.html#t:Caption) data type, which is made up of an optional ShortCaption. I didn't see any mention of a short caption in the [User Guide](https://pandoc.org/MANUAL.html) and also no way to specify one for a table in [Pandoc's Markdown](https://pandoc.org/MANUAL.html#tables). I then assumed that this would be a field utilised by pandoc's LaTeX reader and writer for storing a short caption in LaTeX tables for use in a List of Tables, like so:
```
\caption[short caption]{long caption}
```
However, when I try this using an example `.tex` file containing a table with a caption of the above form, the resulting AST's Table element does not contain a ShortCaption. Hence my assumption that the ShortCaption would be utilised by pandoc's LaTeX reader and writer is wrong. I am thus left wondering what the purpose of the ShortCaption is.

**Comment by jgm** [comment]
That is the purpose.  We just haven't yet supported all the new AST features in the readers and writers.  Adding support to the LaTeX reader should be relatively straightforward, but this won't help much until writers also support this.

**Comment by rnwst** [comment]
Understood, thank you.

**Comment by jgm** [comment]
I just added some code to the LaTeX reader so that the short caption will be parsed and put into  the AST.

**Comment by rnwst** [comment]
That was quick! Thank you! 
I guess it's only a question of time now until someone will complain that the ShortCaption is correctly read in but not used by the LaTeX writer :smile:

**Comment by jgm** [comment]
The LaTeX writer actually does handle it already.

**Comment by rnwst** [comment]
Thanks for clarifying, based on your first comment I had assumed that wouldn't be the case.
