### ISSUE TITLE
Work with a StateT transformator

### ISSUE THREAD

**Issue by KommuSoft** [jgm/pandoc-types#104]
It would be nice if we can also use a `StateT` monad transformer when walking through the AST and thus keep track of the section, and update the state based on content that we see when "walking" over the tree.

**Comment by jgm** [comment]
`walkM` in Text.Pandoc.Walk works for any monad.  So yes, you can use it with a state monad or something else with StateT.  Am I missing something in your question?

**Comment by KommuSoft** [comment]
After rereading, I realized it was missing the most important part: the [`toJSONFilter`](https://hackage.haskell.org/package/pandoc-types-1.22.2.1/docs/Text-Pandoc-JSON.html#v:toJSONFilter) which does not seem to allow effectively walk over this.

The implementation looks like https://github.com/jgm/pandoc-types/blob/da9aeed5f3c5e7ad4d456e5b1e99e7a1573854be/src/Text/Pandoc/JSON.hs#L120-L124

so probably generalizing it to any monad transformer with `IO` as the "outer" one is possible. I will take a look into it.

**Comment by jgm** [comment]
Yes, maybe we could generalize these to any MonadIO instance.
An alternative approach that should work already would be to use the IO Monad and an IORef for state.

**Comment by jgm** [comment]
Closed by #105.
