### ISSUE TITLE
Issue with compiling pandoc-theorem

### ISSUE THREAD

**Issue by dozed** [jgm/pandoc-types#112]
There is an issue compiling [`pandoc-theorem`](https://github.com/sliminality/pandoc-theorem) against `pandoc-types-1.23`:

```
pandoc-theorem/app/Main.hs:8:8: error:
    • No instance for (Text.Pandoc.JSON.ToJSONFilter
                         IO
                         (Text.Pandoc.Definition.Block -> [Text.Pandoc.Definition.Block]))
        arising from a use of ‘toJSONFilter’
        (maybe you haven't applied a function to enough arguments?)
    • In the expression: toJSONFilter $ toList . convertBlock
      In an equation for ‘main’:
          main = toJSONFilter $ toList . convertBlock
  |
8 | main = toJSONFilter $ toList . convertBlock
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The relevant source can be found [here](https://github.com/sliminality/pandoc-theorem/blob/master/app/Main.hs).

`pandoc-theorem` relies on an instance `ToJSONFilter IO (Block -> [Block]` which has been removed in https://github.com/jgm/pandoc-types/commit/183af9d9f1066be974ac55fd23a4c985999d3ce8

Should this issue be fixed on `pandoc-theorem`'s side or could the instance be re-introduced?

**Comment by jgm** [comment]
It should be raised on pandoc-theorem's side.

**Comment by dozed** [comment]
Thanks, the fix has been submitted: https://github.com/sliminality/pandoc-theorem/pull/13
