### ISSUE TITLE
toJSONFilter has no instances to take the "meta"-block into account

### ISSUE THREAD

**Issue by KommuSoft** [jgm/pandoc-types#117]
As far as I can see, the [`ToJSONFilter`](https://hackage.haskell.org/package/pandoc-types-1.23.1/docs/Text-Pandoc-JSON.html#t:ToJSONFilter) typeclass can work with any `Walkable` that is a `Pandoc` , and thus can walk the `Block`s (or lists), `Inline`s (or lists), or `Meta`, but a common usecase would be to walk over the blocks, and have access to the `Meta` for querying, something like:

```
instance (Walkable a Pandoc, MonadIO m) => ToJSONFilter m (Meta -> a -> a) where
    -- ...
```

**Comment by jgm** [comment]
Run it in a `Reader Meta` monad, then you can just `ask`?

**Comment by KommuSoft** [comment]
Ok, but then we need to construct the `runReader` ourselves if I understand it correctly? Perhaps it is nice that there is an instance that could automatically "inject" the data into the `Reader`?

**Comment by jgm** [comment]
No, I'd rather keep it conceptually simple.  If we add an unnecessary instance for every need someone might have, things will get quite cluttered.

**Comment by KommuSoft** [comment]
But just to clarify, it thus will use something like `\Pandoc m bs -> walkM (runReader m) bs`?

**Comment by jgm** [comment]
no, you'd put the runReader outside of walkM.
