### ISSUE TITLE
Unable to build on Docker Hub: `ExitFailure (-9)`

### ISSUE THREAD

**Issue by thriqon** [jgm/pandoc-types#16]
Today, I tried to build `pandoc` via cabal on Docker Hub (which worked before, a few weeks ago), but now I only get an error. I've isolated the problem to `pandoc-types`, but unfortunately I can't make any sense out of the error messages. The Docker container builds correctly on my devices.

This is the output of the latest build: https://hub.docker.com/r/thriqon/full-pandoc/builds/be4dayresfnxycbghqowa65/ (near the bottom is the debug output produced with `-v3`).
The Dockerfile is this one: https://hub.docker.com/r/thriqon/full-pandoc/~/dockerfile/.

Many thanks in advance for any help!

**Comment by jgm** [comment]
I don't see any log output at that URL.

Looking at your Dockerfile,
there are some odd things.  You shouldn't need to install
tls, highlighting-kate, etc. separately.  Try replacing
all those cabal install commands with:

    RUN cabal install pandoc pandoc-citeproc pandoc-crossref

If it still doesn't work, please paste the relevant part of
the build log (giving the error) into this issue.

**Comment by thriqon** [comment]
Sorry, I didn't know you are unable to see the log. I restarted the job once again with the Dockerfile changed as you recommended, but I see the same error. In fact, I had this exact line in place this morning when it started to fail. Here is the log output, it starts when `http-client` has already been installed : https://gist.githubusercontent.com/thriqon/5fbdf5067ecc15d97dd3/raw/4b8c8e4ade6657a82b6674899dae1031cdf5653e/error-log.txt

**Comment by jgm** [comment]
I'm not familiar with the tool that's being used to build
here.  But note the bottom:  Exit Failure (-9). This may be
due to an out-of-memory condition.

Is it possible that your build environment doesn't have
sufficient memory?

+++ Jonas Weber [Oct 19 15 10:39 ]:

**Comment by thriqon** [comment]
I didn't get to fix this issue, so I decided to take the long road: Build the image locally, and push it pre-built into Docker Hub. Thanks anyway, @jgm. Pandoc is awesome!
