### ISSUE TITLE
pandoc-types documentation on hackage is not build properly?

### ISSUE THREAD

**Issue by htdebeer** [jgm/pandoc-types#26]
If I go to http://hackage.haskell.org/package/pandoc-types, I cannot see or open any module such as the Text.Pandoc.Definition module. Some nice Samaritan on #pandoc (irc) pointed me to the source code (https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Definition.hs), which was a big help in finding out the various types and their definition used by pandox,  but formatted api documentation would be nice to have.

**Comment by jgm** [comment]
I don't know why Hackage sometimes doesn't build the
documentation.  But I was able to upload it manually,
so the problem should now be solved.

+++ Huub de Beer [Nov 06 16 08:23 ]:

**Comment by htdebeer** [comment]
Thanks!
