### ISSUE TITLE
block list filters don't get correctly applied to blocks nested in a bullet list or in a table cell

### ISSUE THREAD

**Issue by danse** [jgm/pandoc-types#39]
i stumbled upon the error within a table and than i found out that it applies also to bullet lists, which contain lists of lists of blocks like the tables.

i was not able to extend the property tests in order to reproduce this error. as far as i can see, arbitrary block lists are correctly generated so this case should appear sooner or later. an hypothesis is that `everywhere`, used to double check the correctness of transformations, features the same error ... but it seems unlikely.

in any case i could pinpoint the error with some specific tests, and any suggestion about how to improve them is welcome.

**Comment by jgm** [comment]
This is obviously a serious problem, which we should fix, and having the test case in this repository will help ensure we don't forget, so maybe you could submit a PR with just the failing test, for now?

Trying to reproduce with syb generics and `everything` would also be a good idea.  If the problem can't be reproduced there, we have to wonder why QuickCheck never found the problem, and it would be good to explain that.

**Comment by danse** [comment]
after trying to reproduce with `everything` i took some time to investigate better, using the tests for trial and error. this is not a very elegant methodology but it led me to rewrite the tests as you can see in #42

the core of the error is to use `p_walk` with `blocksTrans` rather than with `blockTrans` like in the existing tests. by doing so we can also trigger errors in the property tests.

after finding this out i came back to my original problem and i found out that it was due to a simpler error, so now my filter featuring a list transformation on blocks works correctly also within bullet lists and table cells.

i think that i made an error writing these tests, and we did not realise the kind of error at first sight. we can probably close this issue and the related pull request

**Comment by jgm** [comment]
I didn't follow all of that -- but, is the upshot here that there isn't a bug in pandoc-types?
If so, we can close this, yes.

**Comment by danse** [comment]
no bug, just confusion between `blocksTrans` and `blockTrans`, and this was one of the few `s` errors that would not be caught by the type system :)
