### ISSUE TITLE
Why do we need isNull?

### ISSUE THREAD

**Issue by josephcsible** [jgm/pandoc-types#67]
https://github.com/jgm/pandoc-types/blob/154b91b37509aae64c71607fe64e88f1274dba5a/Text/Pandoc/Builder.hs#L196-L197

Is there a reason that we need `isNull`?  `Many` is `Foldable`, so isn't it always the same as [`null`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#v:null)? Can we mark it as deprecated now and eventually remove it?

**Comment by jgm** [comment]
I think you're right.  Yes, we could deprecate it.  We should also replace places that use it with `null`.
