### ISSUE TITLE
Use Map for key-value pairs

### ISSUE THREAD

**Issue by josephcsible** [jgm/pandoc-types#70]
https://github.com/jgm/pandoc-types/blob/dd50a6eaeaf63773bbf04d6ef34b86d6f92b7825/Text/Pandoc/Definition.hs#L196

I'm not sure what your policy is on breaking changes, but when/if you next plan to do a breaking release, I think we should consider changing this to `type Attr = (Text, [Text], M.Map Text Text)`.

**Comment by jgm** [comment]
The reason it's a list is to preserve the order in a deterministic way (e.g. in round trips).

**Comment by josephcsible** [comment]
Ah, didn't think of that. I'm not sure how you feel about a dependency, but `ordered-containers` has `Data.Map.Ordered` to handle that. (If you're not a fan of that idea, then feel free to close this.)

**Comment by jgm** [comment]
I guess I'm not convinced that it's worth introducing a new dependency  and changing the API just for this.  (It would be a hassle changing it everywhere.). Generally attribute lists are not too long, so there shouldn't be much performance difference.

**Comment by josephcsible** [comment]
Fair enough.
