### ISSUE TITLE
Broken dependency constraints for pandoc-types 1.20

### ISSUE THREAD

**Issue by gallais** [jgm/pandoc-types#74]
While working on msp-strath/Mary#46, I have noticed that `pandoc-types-1.20`
has the constraint `QuickCheck (>=2.4 && <2.14)` but it uses `liftShrink` in
`Text.Pandoc.Arbitrary` and that was only introduced in `QuickCheck-2.10`.

Is it possible to update the dependencies on hackage? Cheers!

**Comment by jgm** [comment]
I've just done it.

**Comment by gallais** [comment]
Thanks! <3
