### ISSUE TITLE
Tag 1.20 seems to be missing in git

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc-types#82]
There is a release 1.20 on GitHub, but running `git tag` does not include the `1.20` tag; it seems to be missing in git. The commit behind release 1.20 does not appear to be part of any branch; trying to checkout the commit id fails.

**Comment by jgm** [comment]
It's there:

https://github.com/jgm/pandoc-types/releases/tag/1.20

**Comment by jgm** [comment]
Wait, I see what you mean now.  The commit isn't in master.

**Comment by jgm** [comment]
OK.  I don't know why this happened, but dba3a00 was the same as 6817d99, which is in master.  I changed the 1.20 tag to point to the latter.
