### ISSUE TITLE
Pandoc not parsing metadata when invoked inside Haskell program

### ISSUE THREAD

**Issue by mhwombat** [jgm/pandoc-types#87]
I'm writing a Pandoc filter. Within my filter, I want to run Pandoc on _another_ file to extract some information. I didn't find the right way to do this in the Pandoc manual or the Haddoc documentation, so I made my best guess.  Unfortunately, the metadata isn't parsed correctly.

Here's a file (`test.md`) I want to parse from within my code:

```
---
title: This is a test
...

Hello world!
```

Here's a tiny program demonstrating the issue:

```
import Text.Pandoc.Class (PandocIO, readFileStrict, runIOorExplode)
import Text.Pandoc.JSON (Pandoc)
import Text.Pandoc.Readers (readMarkdown)
import Text.Pandoc.Options (def)
import Text.Pandoc.UTF8 (toText)

main :: IO ()
main = do
  doc <- runIOorExplode $ readTitle "test.md"
  putStrLn . show $ doc

readTitle :: FilePath -> PandocIO Pandoc
readTitle f = do
  s <- readFileStrict f
  let t = toText s
  md <- readMarkdown def t
  return md

```

When I run the program, I get:

```
Pandoc (Meta {unMeta = fromList []}) [HorizontalRule,Para [Str "title:",Space,Str "This",Space,Str "is",Space,Str "a",Space,Str "test",SoftBreak,Str "..."],Para [Str "Hello",Space,Str "world!"]]
```

But if I parse it from the command line, Pandoc correctly picks up the metadata.

```
$ pandoc -s -t native test.md
Pandoc (Meta {unMeta = fromList [("title",MetaInlines [Str "This",Space,Str "is",Space,Str "a",Space,Str "test"])]})
[Para [Str "Hello",Space,Str "world!"]]

```

**Comment by jgm** [comment]
This should really go to pandoc, not pandoc-types.
But the answer is simple:  you're using default reader options (`def`).  By default, `readerStandalone` is disabled, and that disables metadata reading.

**Comment by jgm** [comment]
By the way, if you think this behavior is unintuitive, you're not the only one. There's an active discussion here:
https://groups.google.com/d/msgid/pandoc-discuss/87czzbq940.fsf%40zeitkraut.de
